apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-load-test-hpa
  namespace: my-load-test-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-load-test-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
